/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author kevin
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CountSW = new javax.swing.JLabel();
        CountST = new javax.swing.JLabel();
        SW = new javax.swing.JLabel();
        ST = new javax.swing.JLabel();
        IA = new javax.swing.JLabel();
        StatsSW = new javax.swing.JLabel();
        SW2 = new javax.swing.JLabel();
        SW3 = new javax.swing.JLabel();
        SW4 = new javax.swing.JLabel();
        SW5 = new javax.swing.JLabel();
        SW6 = new javax.swing.JLabel();
        SW7 = new javax.swing.JLabel();
        SW8 = new javax.swing.JLabel();
        SW9 = new javax.swing.JLabel();
        SW10 = new javax.swing.JLabel();
        StatsST = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CountSW.setBackground(new java.awt.Color(255, 255, 255));
        CountSW.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        CountSW.setForeground(new java.awt.Color(255, 255, 51));
        CountSW.setText("0");
        jPanel1.add(CountSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 80, 60));

        CountST.setBackground(new java.awt.Color(255, 255, 255));
        CountST.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        CountST.setForeground(new java.awt.Color(255, 0, 51));
        CountST.setText("0");
        jPanel1.add(CountST, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 30, 60));

        SW.setBackground(new java.awt.Color(255, 255, 255));
        SW.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        SW.setForeground(new java.awt.Color(255, 255, 51));
        SW.setText("Star Wars");
        jPanel1.add(SW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 60));

        ST.setBackground(new java.awt.Color(255, 255, 255));
        ST.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        ST.setForeground(new java.awt.Color(255, 0, 51));
        ST.setText("Star Trek");
        jPanel1.add(ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 110, 60));

        IA.setBackground(new java.awt.Color(255, 255, 255));
        IA.setFont(new java.awt.Font("Segoe UI Symbol", 1, 20)); // NOI18N
        IA.setForeground(new java.awt.Color(255, 255, 255));
        IA.setText("IA Descansando zzz zzz zzz zzz zzz zzz zzz zzz zzz zzz zzz zzz zzz zzz zzz");
        IA.setToolTipText("");
        jPanel1.add(IA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 600, 60));

        StatsSW.setBackground(new java.awt.Color(255, 255, 255));
        StatsSW.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        StatsSW.setForeground(new java.awt.Color(255, 255, 255));
        StatsSW.setText("Stats Star Wars");
        jPanel1.add(StatsSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 130, 130));

        SW2.setBackground(new java.awt.Color(255, 255, 255));
        SW2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW2.setForeground(new java.awt.Color(255, 0, 51));
        SW2.setText("Refuerzo");
        jPanel1.add(SW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 190, 60));

        SW3.setBackground(new java.awt.Color(255, 255, 255));
        SW3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW3.setForeground(new java.awt.Color(255, 255, 51));
        SW3.setText("Prioridad 2");
        jPanel1.add(SW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 60));

        SW4.setBackground(new java.awt.Color(255, 255, 255));
        SW4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW4.setForeground(new java.awt.Color(255, 255, 51));
        SW4.setText("Prioridad 3");
        jPanel1.add(SW4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 190, 60));

        SW5.setBackground(new java.awt.Color(255, 255, 255));
        SW5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW5.setForeground(new java.awt.Color(255, 255, 51));
        SW5.setText("Prioridad 1");
        jPanel1.add(SW5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 60));

        SW6.setBackground(new java.awt.Color(255, 255, 255));
        SW6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW6.setForeground(new java.awt.Color(255, 0, 51));
        SW6.setText("Prioridad 1");
        jPanel1.add(SW6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 190, 60));

        SW7.setBackground(new java.awt.Color(255, 255, 255));
        SW7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW7.setForeground(new java.awt.Color(255, 0, 51));
        SW7.setText("Prioridad 2");
        jPanel1.add(SW7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 190, 60));

        SW8.setBackground(new java.awt.Color(255, 255, 255));
        SW8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW8.setForeground(new java.awt.Color(255, 0, 51));
        SW8.setText("Prioridad 3");
        jPanel1.add(SW8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 190, 60));

        SW9.setBackground(new java.awt.Color(255, 255, 255));
        SW9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        SW9.setForeground(new java.awt.Color(255, 255, 51));
        SW9.setText("Refuerzo");
        jPanel1.add(SW9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 190, 60));

        SW10.setBackground(new java.awt.Color(255, 255, 255));
        SW10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        SW10.setForeground(new java.awt.Color(255, 255, 255));
        SW10.setText("Ganadores");
        jPanel1.add(SW10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 100, 60));

        StatsST.setBackground(new java.awt.Color(255, 255, 255));
        StatsST.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        StatsST.setForeground(new java.awt.Color(255, 255, 255));
        StatsST.setText("Stats Star Trek");
        jPanel1.add(StatsST, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 130, 140));

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 100, 50));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 320, 90));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 160, 70));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 160, 70));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 160, 70));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 160, 70));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 70));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 160, 70));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane9.setViewportView(jTextArea8);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 160, 70));

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane10.setViewportView(jTextArea9);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carta inicio st.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 190, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carta inicio.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diseño sin título (3).png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CountST;
    private javax.swing.JLabel CountSW;
    private javax.swing.JLabel IA;
    private javax.swing.JLabel ST;
    private javax.swing.JLabel SW;
    private javax.swing.JLabel SW10;
    private javax.swing.JLabel SW2;
    private javax.swing.JLabel SW3;
    private javax.swing.JLabel SW4;
    private javax.swing.JLabel SW5;
    private javax.swing.JLabel SW6;
    private javax.swing.JLabel SW7;
    private javax.swing.JLabel SW8;
    private javax.swing.JLabel SW9;
    private javax.swing.JLabel StatsST;
    private javax.swing.JLabel StatsSW;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
